<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>zhaodai</AssemblyName>
    <RootNamespace>ZhaDai.Cli</RootNamespace>
    <Version>0.1.2-alpha</Version>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZhaDai.Core\ZhaDai.Core.csproj" />
  </ItemGroup>

</Project>
