<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>ZhaDai.Core.Tests</AssemblyName>
    <RootNamespace>ZhaDai.Core.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ZhaDai.Core\ZhaDai.Core.csproj" />
    <ProjectReference Include="..\..\src\ZhaDai.Automation\ZhaDai.Automation.csproj" />
  </ItemGroup>

</Project>
